package xg.efacturador;

public class EFacturadorTest {
	
	//TEST ERROR EN LA GENERACION, EMITIR AVISO
	
	//TEST ERROR EN EL ENVIO, EMITIR AVISO
	
	//TEST SE GENERÓ BIEN, SE GUARDA EN LA BASE DE DATOS CORRECTAMENTE, ERROR EN EL ENVIO, QUEDA PENDIENTE
	
	//TEST SE GENERÓ BIEN, SE GUARDA EN LA BASE DE DATOS CORRECTAMENTE, ERROR EN EL ENVIO, QUEDA PENDIENTE
	


}
